import { Link } from 'react-router-dom';
import DocPage, { Section, Bullets } from '../components/legal/DocPage';

/*
 * Written from a verified inventory of what the code actually does, not
 * from a template. Every claim here was checked against the implementation;
 * where something could not be established from the repo, the wording is
 * deliberately conservative rather than reassuring.
 */
function Privacy() {
  return (
    <DocPage
      title="Privacy"
      updated="September 5, 2026"
      intro="Kynd is an independent portfolio demonstration. This page describes what the demo actually stores, why, and for how long — in plain English."
    >
      <Section title="The short version">
        <Bullets
          items={[
            'There is no signup or login, and Kynd does not ask for your real name, email address, password, or other account credentials.',
            'You get a temporary demo account so the product can remember what you did while you explore.',
            'Kynd sets no cookies and runs no analytics or advertising.',
            'Your demo activity is visible only to you.',
            'Please do not enter sensitive personal information into a demo.',
          ]}
        />
      </Section>

      <Section title="What Kynd stores">
        <p>
          When you open Kynd, the server creates a temporary demo session and a placeholder demo user
          for it. That user has a fixed placeholder name and city used for every visitor — it is not
          about you and is not derived from anything you provide.
        </p>
        <p>As you use the demo, Kynd stores the actions you take:</p>
        <Bullets
          items={[
            'Opportunities you join or leave, and ones you save',
            'People and organizations you follow',
            'Reactions you add and comments you write',
            'Activities you log, including any hours and story text you choose to write',
            'Opportunities and fundraisers you create, including their descriptions',
            'Simulated fundraiser support, including the amount you selected',
            'The starter cause interests attached to your temporary account',
          ]}
        />
        <p>
          Anything you type — a comment, a story, a title, a description — is stored as you wrote
          it, because the demo has to display it back to you. That is the main reason to keep
          personal details out of it.
        </p>
      </Section>

      <Section title="What Kynd does not collect">
        <p>
          Kynd&rsquo;s application code does not ask for or intentionally store your name, email
          address, phone number, postal address, payment details, precise location, or any account
          credentials. There is nothing to sign up for.
        </p>
      </Section>

      <Section title="Browser storage">
        <p>
          Kynd stores one value in your browser&rsquo;s localStorage: a randomly generated demo
          session identifier, under the key <code className="text-[13px]">kynd_demo_session_id</code>.
          It is an opaque identifier generated by the server — it contains no information about you.
        </p>
        <p>
          That is the only thing Kynd puts in your browser.{' '}
          <strong className="font-semibold text-ink">Kynd sets no cookies</strong>, and localStorage
          is not a cookie. Clearing your browser storage simply means the demo will start you a new
          session next time.
        </p>
      </Section>

      <Section title="Why this information is used">
        <p>It is used only to operate the demo:</p>
        <Bullets
          items={[
            'To remember your actions while you explore, so joining something actually persists',
            'To show your contribution history and profile',
            'To make social features such as follows, reactions, and comments work',
            'To keep each visitor’s demo separate from every other visitor’s',
          ]}
        />
        <p>
          It is not used for marketing, profiling, advertising, or any purpose beyond running the
          demonstration.
        </p>
      </Section>

      <Section title="What other visitors can see">
        <p>
          Nothing you do. The demo shows you the synthetic seeded community plus your own actions,
          and nothing else. Another visitor&rsquo;s joins, follows, comments, reactions, saves, and
          created content are never visible to you, and yours are never visible to them — including
          in participant counts, follower counts, and fundraiser totals.
        </p>
      </Section>

      <Section title="How long it lasts">
        <p>These are three separate things, and it is worth being precise about them:</p>
        <Bullets
          items={[
            'Expiry — a demo session becomes invalid 24 hours after it is created. Once expired, it can no longer be used and your demo starts fresh.',
            'Cleanup — expiry does not immediately erase the underlying database rows. Expired sessions and their data are deleted opportunistically, in small batches, when new sessions are created. In practice this happens soon after, but it is not instantaneous and there is no scheduled job guaranteeing a specific time.',
            'Reset — choosing Reset demo deletes your session and its data immediately, rather than waiting for cleanup.',
          ]}
        />
      </Section>

      <Section title="Reset demo">
        <p>
          Reset deletes your demo session from the database. Because of how the database is
          structured, deleting the session also deletes your temporary user and everything linked to
          it — joins, saves, follows, reactions, comments, logged activities and their stories,
          fundraiser support, and any opportunities or fundraisers you created. The synthetic
          community itself is unchanged.
        </p>
        <p>
          To be accurate about what Reset is not: it deletes application data. It is not a guarantee
          that every operational record held by the hosting providers below — server logs, database
          backups, network logs — disappears at the same moment. Those are outside Kynd&rsquo;s
          control and follow each provider&rsquo;s own practices.
        </p>
      </Section>

      <Section title="Service providers">
        <p>Kynd runs on third-party infrastructure. Operating a website necessarily means these providers process technical information about your request, such as your IP address, browser and device information, and timestamps.</p>
        <Bullets
          items={[
            'Cloudflare Pages serves the website and its images, and provides network and security functions.',
            'Render runs the API server that handles your demo actions.',
            'Neon hosts the PostgreSQL database where demo data is stored.',
            'Google Fonts serves the typeface used by the site. Because your browser requests the font file directly from Google, Google receives your IP address and browser information when the page loads. Kynd does not intentionally send your demo content or session data to Google.',
          ]}
        />
        <p>
          Kynd&rsquo;s own application code does not intentionally record IP addresses or browser
          user-agent strings. That is a statement about Kynd&rsquo;s code, not about the providers —
          they may process and retain such technical information as part of delivering their
          services, according to their own policies.
        </p>
      </Section>

      <Section title="Server logs">
        <p>
          Kynd&rsquo;s application logging is intentionally minimal. When an unexpected error
          occurs, the server records a short error message and error code. It does not log request
          bodies, comment text, activity stories, titles, descriptions, or session identifiers.
        </p>
        <p>Hosting providers keep their own operational logs, as described above.</p>
      </Section>

      <Section title="Analytics and advertising">
        <p>
          <strong className="font-semibold text-ink">
            Kynd currently runs no product analytics and no third-party tracking.
          </strong>{' '}
          There is no analytics SDK, no tracking pixel, no advertising network, and no
          behavioural profiling.
        </p>
        <p>
          Analytics for this demo have been designed but are not implemented. If that changes, this
          page will be updated before or when it ships, and will describe what is actually
          collected.
        </p>
        <p>
          Kynd does not sell information about visitors, and does not use visitor information for
          behavioural advertising.
        </p>
      </Section>

      <Section title="Artificial intelligence">
        <p>
          AI-assisted development tools were used while building Kynd. The running demo does not use
          a generative AI model to create anything you see or to make product decisions, and what
          you enter in the demo is not sent by Kynd to any AI model or AI provider.
        </p>
      </Section>

      <Section title="Please don't enter sensitive information">
        <p>
          Kynd is a public demonstration. Please do not enter personal, sensitive, confidential, or
          identifying information anywhere in it — including in comments, activity stories, and the
          descriptions of anything you create. Treat everything you type here as demo content.
        </p>
      </Section>

      <Section title="Children">
        <p>
          Kynd is not directed to children under 13 and is not intended for use by children under
          13.
        </p>
      </Section>

      <Section title="Changes">
        <p>
          This is an evolving portfolio project. If its data practices change materially, this page
          will be updated and the date at the top will change.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Kynd is a personal portfolio project maintained by its author. Questions about it can be
          raised through the{' '}
          <a
            href="https://github.com/sjha27/kynd"
            target="_blank"
            rel="noreferrer noopener"
            className="font-semibold text-brand underline underline-offset-2"
          >
            project&rsquo;s public source repository
          </a>
          .
        </p>
      </Section>

      <Section title="Related">
        <p>
          <Link to="/demo-info" className="font-semibold text-brand underline underline-offset-2">
            About this demo
          </Link>{' '}
          &middot;{' '}
          <Link to="/terms" className="font-semibold text-brand underline underline-offset-2">
            Terms &amp; demo disclaimer
          </Link>
        </p>
      </Section>
    </DocPage>
  );
}

export default Privacy;
