'use strict';

const crypto = require('node:crypto');

const demoSessionQueries = require('../db/queries/demo_sessions');
const { SessionError } = require('../errors');

/*
 * The temporary visitor.
 *
 * Deliberately empty: a neutral name and the minimum the frozen schema
 * requires (display_name, city and state are NOT NULL; avatar_url and bio are
 * nullable and stay null). No bio, no causes, no follows, no history.
 *
 * The visitor is NOT Maya or any other seeded identity — they are a new,
 * empty participant arriving in an already-alive Atlanta community, so their
 * profile should start genuinely blank and only fill through their own
 * actions in later slices.
 *
 * Atlanta/GA because the seeded world is an Atlanta ecosystem and `state`
 * is constrained to a two-letter code.
 */
const VISITOR = Object.freeze({
  displayName: 'Kynd Visitor',
  city: 'Atlanta',
  state: 'GA',
});

// Product-facing shape. No database internals, no session bookkeeping
// columns, nothing about other users.
function toPublicSession(row) {
  return {
    sessionId: row.session_id ?? row.id,
    expiresAt: row.session_expires_at ?? row.expires_at,
    user: {
      id: row.user_id,
      name: row.user_display_name,
    },
  };
}

async function createDemoSession() {
  // Both ids are generated by the backend with the platform CSPRNG. The
  // browser never supplies or influences an identifier, and these are
  // intentionally random rather than deterministic: temporary visitor state
  // is infrastructure, not part of the reproducible seeded world.
  const sessionId = crypto.randomUUID();
  const userId = crypto.randomUUID();

  const { session, user } = await demoSessionQueries.createSessionWithUser({
    sessionId,
    userId,
    displayName: VISITOR.displayName,
    city: VISITOR.city,
    state: VISITOR.state,
  });

  return toPublicSession({
    session_id: session.id,
    session_expires_at: session.expires_at,
    user_id: user.id,
    user_display_name: user.display_name,
  });
}

/*
 * Resolves a session id, or throws SessionError.
 *
 * Unknown and expired are intentionally indistinguishable to the caller so
 * this cannot be used to probe which session ids exist.
 */
async function resolveDemoSession(sessionId) {
  const row = await demoSessionQueries.findActiveSession(sessionId);
  if (!row) {
    throw new SessionError();
  }
  return {
    sessionId: row.session_id,
    expiresAt: row.session_expires_at,
    user: {
      id: row.user_id,
      name: row.user_display_name,
      city: row.user_city,
      state: row.user_state,
    },
  };
}

function toPublicContext(context) {
  return {
    sessionId: context.sessionId,
    expiresAt: context.expiresAt,
    user: { id: context.user.id, name: context.user.name },
  };
}

module.exports = {
  VISITOR,
  createDemoSession,
  resolveDemoSession,
  toPublicContext,
};
