'use strict';

const crypto = require('node:crypto');

const demoSessionQueries = require('../db/queries/demo_sessions');
const { SessionError } = require('../errors');
const {
  PERSONA,
  STARTER_CAUSE_IDS,
  STARTER_FOLLOWED_USER_IDS,
  STARTER_FOLLOWED_ORGANIZATION_IDS,
} = require('../config/demo_persona');

/*
 * The temporary visitor.
 *
 * Lightly established, not blank: a starter cause affinity and a small
 * starter social graph (see config/demo_persona.js) so a recruiter opens
 * something that already feels like an existing social account, while
 * avatar_url and bio stay null (monogram fallback) and no activity,
 * registration, or contribution history is fabricated — that part of the
 * product is still the recruiter's to do.
 *
 * The visitor is NOT Maya or any other seeded identity — a new participant
 * arriving in an already-alive Atlanta community, with an empty history that
 * only fills through their own actions.
 *
 * Atlanta/GA because the seeded world is an Atlanta ecosystem and `state`
 * is constrained to a two-letter code.
 */
const VISITOR = Object.freeze({
  displayName: PERSONA.displayName,
  city: PERSONA.city,
  state: PERSONA.state,
});

// Product-facing shape. No database internals, no session bookkeeping
// columns, nothing about other users.
function toPublicSession(row) {
  return {
    sessionId: row.session_id ?? row.id,
    expiresAt: row.session_expires_at ?? row.expires_at,
    user: {
      id: row.user_id,
      name: row.user_display_name,
    },
  };
}

async function createDemoSession() {
  // Both ids are generated by the backend with the platform CSPRNG. The
  // browser never supplies or influences an identifier, and these are
  // intentionally random rather than deterministic: temporary visitor state
  // is infrastructure, not part of the reproducible seeded world.
  const sessionId = crypto.randomUUID();
  const userId = crypto.randomUUID();

  const { session, user } = await demoSessionQueries.createSessionWithUser({
    sessionId,
    userId,
    displayName: VISITOR.displayName,
    city: VISITOR.city,
    state: VISITOR.state,
    causeIds: STARTER_CAUSE_IDS,
    followedUserIds: STARTER_FOLLOWED_USER_IDS,
    followedOrganizationIds: STARTER_FOLLOWED_ORGANIZATION_IDS,
  });

  return toPublicSession({
    session_id: session.id,
    session_expires_at: session.expires_at,
    user_id: user.id,
    user_display_name: user.display_name,
  });
}

/*
 * Resolves a session id, or throws SessionError.
 *
 * Unknown and expired are intentionally indistinguishable to the caller so
 * this cannot be used to probe which session ids exist.
 */
async function resolveDemoSession(sessionId) {
  const row = await demoSessionQueries.findActiveSession(sessionId);
  if (!row) {
    throw new SessionError();
  }
  return {
    sessionId: row.session_id,
    expiresAt: row.session_expires_at,
    user: {
      id: row.user_id,
      name: row.user_display_name,
      city: row.user_city,
      state: row.user_state,
    },
  };
}

/*
 * Reset: end this visitor's demo and discard everything they did.
 *
 * Backend deletion is authoritative — clearing localStorage alone would
 * leave the temporary user and all their rows behind, and the next visitor
 * to that browser would have no way to reach or clean them.
 *
 * The caller has already been resolved by requireDemoSession, so a visitor
 * can only ever reset their OWN session; the id is never taken from a body.
 */
async function resetDemoSession(sessionId) {
  await demoSessionQueries.deleteSession(sessionId);
}

function toPublicContext(context) {
  return {
    sessionId: context.sessionId,
    expiresAt: context.expiresAt,
    user: { id: context.user.id, name: context.user.name },
  };
}

module.exports = {
  VISITOR,
  createDemoSession,
  resolveDemoSession,
  resetDemoSession,
  toPublicContext,
};
